# Generated by Django 4.2.15 on 2024-10-10 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_employerdetail_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerdetail',
            name='employer',
        ),
    ]
