# Generated by Django 4.2.15 on 2024-10-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_phone_number_employerdetail_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerdetail',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
