# Generated by Django 4.2.15 on 2024-10-11 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='parent_Id',
        ),
    ]
