# Generated by Django 4.2.15 on 2024-10-14 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_employerdetail_company_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerdetail',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='employerdetail',
            name='mobile_number',
        ),
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_details', to='user.employerdetail')),
            ],
        ),
    ]
