# Generated by Django 4.2.15 on 2024-10-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_companydetails_alter_contactdetail_employer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='BusinessRegistrationNumber',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='TaxIdentificationNumber',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
