# Generated by Django 4.2.15 on 2024-10-14 09:55

from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_companydetails_businessregistrationnumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('document', models.FileField(blank=True, null=True, upload_to=user.models.file_location)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='user.companydetails')),
            ],
        ),
    ]
